version: "3.9"

test_mode: false
jwt_secret_key: "bwrMY2iQTYBa3ZFIYH988RxP4G4fucvhXVQAxkxcJaAjooeQ6TG8XtWqK1IAgGUk"
api_url: "http://localhost:8888"
swagger_port: 6060

redis:
  address: "redis:6379"
  password: ""

mongodb:
  uri: "mongodb://root:example@mongo:27017"
  database: "message_brokers"

servers:
  user:
    address: ":8000"

rabbit_mq:
  username: "guest"
  password: "guest"
  host: "localhost"
  vhost: ""